name: CrystalPoinrts
main: com.caxerx.mc.crystalpoints.CrystalPoinrts
version: 1.2
api-version: 1.13
loadbefore: [BossShop]
commands:
 crystal:
  aliases: [crystals, points, cry, pt]
  description: "CrystalPoinrts command"
permissions:
  crystalpoints.check:
    default: true
    description: Check their own balance.
  crystalpoints.check.other:
    default: op
    description: Check others balance.
  crystalpoints.modify:
    default: op
    description: Modify balance of a player.
  crystalpoints.reload:
    default: op
    description: Reload plugin.